/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ContextRouteImport } from './routes/context'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueIndexRouteImport } from './routes/queue.index'
import { Route as QueueIdRouteImport } from './routes/queue.$id'

const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIdRoute = QueueIdRouteImport.update({
  id: '/queue/$id',
  path: '/queue/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/conversations': typeof ConversationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/queue/$id': typeof QueueIdRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/conversations': typeof ConversationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/queue/$id': typeof QueueIdRoute
  '/queue': typeof QueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/conversations': typeof ConversationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/queue/$id': typeof QueueIdRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/context'
    | '/conversations'
    | '/login'
    | '/register'
    | '/rules'
    | '/settings'
    | '/simulate'
    | '/queue/$id'
    | '/queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/context'
    | '/conversations'
    | '/login'
    | '/register'
    | '/rules'
    | '/settings'
    | '/simulate'
    | '/queue/$id'
    | '/queue'
  id:
    | '__root__'
    | '/'
    | '/context'
    | '/conversations'
    | '/login'
    | '/register'
    | '/rules'
    | '/settings'
    | '/simulate'
    | '/queue/$id'
    | '/queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextRoute: typeof ContextRoute
  ConversationsRoute: typeof ConversationsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SimulateRoute: typeof SimulateRoute
  QueueIdRoute: typeof QueueIdRoute
  QueueIndexRoute: typeof QueueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$id': {
      id: '/queue/$id'
      path: '/queue/$id'
      fullPath: '/queue/$id'
      preLoaderRoute: typeof QueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextRoute: ContextRoute,
  ConversationsRoute: ConversationsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SimulateRoute: SimulateRoute,
  QueueIdRoute: QueueIdRoute,
  QueueIndexRoute: QueueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
